version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    platform: linux/amd64
    build: .
    image: daysond/node-app
    environment:
      - PORT=3000
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dayson
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis


volumes:
  mongo-db: